netneurolab/neuromaps

brainnotation/images.py

This will only impact usage of `images.annot_to_gifti()` and `images.relabel_gifti()`, wherein users providing annotation and/or gifti files that have negative labels will find those labels are automatically set to the background value (0). Because, honestly, who uses negative labels? :monocle_face: 
Will try and create tests for the impacted functions (since none exist right now!).

[REF] Labels <0 are set to 0

---

README.rst
docs/api.rst
docs/installation.rst
examples/plot_spatial_nulls.py
neuromaps/__init__.py
neuromaps/stats.py
neuromaps/tests/test_stats.py

Makes `stats.correlate_images()` more generic `stats.compare_images()`, which accepts any user-provided similarity metric callable (in addition to `'pearsonr'` and `'spearmanr`', as before).
Also updates `stats.permtest_pearsonr()` --> `stats.permtest_metric()` to reflect changes.

[REF] Overhauls `stats.correlate_images()`

---

neuromaps/datasets/_osf.py
neuromaps/datasets/annotations.py
neuromaps/datasets/data/osf.json
neuromaps/datasets/tests/test_utils.py
neuromaps/datasets/utils.py

Screwed up OSF token env variable name when migrating repository.
Also, fixes to `osf.json` tag formatting and other minor changes to `neuromaps.datasets._osf` functions for internal use.

[FIX] Fix OSF info and json

---

neuromaps/images.py
neuromaps/nulls/__init__.py
neuromaps/nulls/nulls.py
neuromaps/nulls/tests/test_nulls.py
neuromaps/transforms.py

A first pass towards being able to generate null maps for volumetric images. The primary issue I'm running into here is that this is computationally...I don't wanna say _impossible_, but basically impossible. If you're working with 1mm isotropic data in MNI152, by default you've got upwards of 1.8 million voxels. The distance matrix ends up being *many* terabytes :grimacing: 
Will consider ways around this... Potentially thresholding the distance matrix based on a KNN regime, where users supply the desired K as a distance (i.e., "10mm")?

[FIX] Fixes handling of volumetric maps for null models

---

neuromaps/datasets/_osf.py
neuromaps/datasets/data/osf.json

Migrates some of the annotations to the public OSF repo, fixed the OSF json, and some light modifications to the `datasets._osf` functionality to make updating the json easier in the future.

[REF] Fix OSF json and funcs

---

neuromaps/datasets/data/osf.json

I uploaded new versions of the MNI1521mm.tar.gz and MNI1522mm.tar.gz. Those new files contain 6Asym versions of the T1w brain map and of the brainmask. I updated the osf.json with the new md5 key.
IMPORTANT: I unintentionally deleted the old version of the MNI1521mm file, which means that old versions of the toolbox won't be able to fetch the 1mm atlases. We should therefore try to release a new version of the toolbox ASAP.

[ENH] New versions of MNI1521mm and MNI1522mm

---

neuromaps/datasets/atlases.py
neuromaps/nulls/nulls.py
neuromaps/nulls/spins.py
neuromaps/stats.py
neuromaps/transforms.py
requirements.txt

This pull request fixes the bugs reported in Issue #27, as well as a few other unreported bugs. The main changes are:
- Added a try-except statement to clean-up temporary files when an error is raised in _vol_surrogates() function.
- WindowsPath object fetched using fetch_atlas() is now converted to a str in the mni152_to_mni152() function. This fixes an Error happening when load_niimg(), a nibabel function, is called.
- In the _make_surrogates() function, when genfunc() is called as _vol_surrogates(), an error was raised because n_proc is not a valid argument. The function call was modified so that n_proc is now a keyword argument.
- The function call to genfunc() in the _make_surrogates() function was modified so that n_proc is now a keyword argument. This fixes an issue happening when …

Fix spatial null maps for volumetric data

---

neuromaps/transforms.py

The function `mni152_to_mni152()` calls the nilearn function `resample_to_img()`, but this function calls `_utils.niimg.load_niimg()`, which currently does not support path-like objects (e.g. `pathlib.Path` objects). Calling this function using path-like objects currently results in a `TypeError`. I fixed this bug by calling `load_nifti()` on the img and target objects before calling `resample_to_img()` in the `mni152_to_mni152()` function.

[FIX] Fix unsupported path-like objects for mni152_to_mni152()

---

.zenodo.json
neuromaps/parcellate.py

- Fixed license in .zenodo.json
- Also fixed a typo in parcellate.py

[FIX] Fixed license

---

neuromaps/images.py
neuromaps/stats.py

I fixed the `UnboundLocalError` that was sometimes raised when calling `load_data()` with array-like data. This fixes, among other things, the issue discussed in PR #34: `stats.compare_images` now works with parcellated data. I modified the docstring of the function accordingly. 
This commit also modifies the docstrings of `load_nifti()` and `load_data()`: I added explanations on how this function handles different `data` types.
Thanks @fmilisav for doing a lot of digging on this!

[FIX] Fixed UnboundLocalError in load_data

---

neuromaps/parcellate.py

This PR fixes a bug in the `inverse_transform` function, which is discussed in [Issue#59](https://github.com/netneurolab/neuromaps/issues/59). As described, we fixed the issue by removing the self.drop argument from the function call to `parcel_to_vertices`.

[FIX] Fixed bug in inverse_transform function

---

neuromaps/resampling.py
neuromaps/transforms.py

This PR fixes [Issue#24](https://github.com/netneurolab/neuromaps/issues/24): a bug in `resample_images` that would happen when a single str or os.PathLike object specifies the path to single-hemispheric `src` or `trg` images. This bug would happen when `resample_images`would try to load the gifti file of the un-transformed map. A call to the `tranforms._check_hemi` function fixes the issue.

[FIX] Fix bug in resample_images

---

tools/install_dependencies.sh

Part failure due to dns resolve error. Not sure the root cause, tried 1) [this](https://github.com/actions/virtual-environments/issues/798) and 2) adding a random sleep, both did not work. Adding retry to wget seems to work. See [this link](https://superuser.com/questions/493640/how-to-retry-connections-with-wget) for parameter settings. Temporary patch.

[FIX] Update install_dependencies.sh to resolve wget dns failure

---

neuromaps/nulls/spins.py
neuromaps/parcellate.py
neuromaps/plotting.py

This commit adds an `ignore_background_data` parameter and a `background_value` parameter in the `transform` method of the `Parcellater` class. These parameter are useful for when the image that we want to parcellate has background data values that should be ignored (see the discussion in Issue #66 as an example). This commit also fixes other minor bugs. The major changes are as follows:
spins.py:
- Added `background` parameter to `vertices_to_parcels` function.
parcellate.py:
- Added `ignore_background_data` and `background_value` parameter to the `transform` method of the `Parcellater` class. See their description in the docstring of the method for more information on how they work.
- Fixed a bug happening when using the `transform` method with volumetric maps and `resampling_target` of …

[ENH] new "ignore_background_data" parameter in Parcellater + other minor fixes

---

docs/user_guide/annotations.rst
docs/user_guide/transformations.rst
neuromaps/datasets/annotations.py
neuromaps/datasets/data/osf.json

I've made some changes related to Issue #81 including:
- added `fsaverage` maps for [beliveau2017](https://xtra.nru.dk/FS5ht-atlas/) and [norgaard2021](https://xtra.nru.dk/BZR-atlas/) data 
- added a warning to the docs (under "transformations") about volume-to-surface transformations of PET data
- added a warning that gets printed whenever users fetch `beliveau2017` or `norgaard2021` data in `MNI152` space, that says that the `fsaverage` versions should be used instead

[ENH] Changes related to Issue #81

---

neuromaps/stats.py

This PR fixes a bug in `compare_images`.
`nan` values were dropped from `srcdata` and `trgdata` regardless of whether `nan_policy` was set to `omit` or `propagate`. This is not what we want: we want to keep the `nan` values when `nan_policy` is set to `propagate`, so that the metric function can handle these values however it wants.
This bug might be related to issue #77.

[FIX] Fix nan_policy related bug in compare_images

---

neuromaps/nulls/nulls.py

This PR fixes bugs in `nulls.burt2018` and `nulls.moran` encountered when trying to generate surrogate brain maps with a volumetric surface and without parcellation: the `hdist` matrix, which stores the distance between each voxel in the image, was being returned sorted. This is required for the `nulls.burt2020` function, but not for `nulls.burt2018` nor `nulls.moran`. I fixed this bug by unsorting the distance matrices when we use these two functions with a volumetric surface and without parcellation. This is a *temporary fix* as sorting, then unsorting the distance matrix is quite innefficient.
I also fixed another bug that prevented us from passing `**kwargs` to the `nulls.moran` function.

[FIX] Fix bugs in burt2018 and moran nulls

---

neuromaps/datasets/data/osf.json

I swapped the order for right and left annotation information in the osf.json file for beliveau2017 and norgaard2021 fsaverage maps. This does not change any data, it just changes the order in which R and L are fetched using neuromaps functionality. Now, when these maps are fetched, tuples will be ordered (L, R) instead of (R, L).

[FIX] Fix order of hemispheres in beliveau and norgaard fsaverage maps

---

neuromaps/datasets/data/osf.json

This PR fixes the URLs of two annotation files, which were accidently modified in previous pull requests. This commit fixes Issue #99

[FIX] Fixed URLs for annotation files

---

README.rst
docs/citing.rst
docs/user_guide/annotations.rst

Updated the README and the docs to list the papers to cite for different functionalities (transformations, spatial nulls) and the brain annotations. This is an expansion of PR #107.

[ENH] Update docs and readme to highlight citations

---

.readthedocs.yaml

This commit adds a `.readthedocs.yaml` files, to comply with the new readthedocs requirements (see [here](https://blog.readthedocs.com/migrate-configuration-v2/) for more details)

[FIX] Add .readthedocs.yaml

---

neuromaps/parcellate.py

This fixes the FutureWarning raised when importing `NiftiLabelsMasker`. Thanks to @LeonDLotter for pointing this out in Issue #116

[FIX] Fix FutureWarning for `nilearn.input_data`

---

neuromaps/resampling.py

In `resampling.resample_images` we were checking if `src` and `src` are in MNI152 space; it's now fixed and checks if `src` and `trg` are in MNI152 space. This PR was prompted by issue #89 .

[FIX] fix bug in resampling.py when src and trg are in MNI152

---

neuromaps/stats.py

Changed 1 line of code to make `stats.compare_images()` compatible with metrics (e.g. `scipy.spatial.distance.cosine`) that may return an int instead of a float. (This PR is related to issue #103 )

[FIX] stats.compare_images compatible with more metrics

---

neuromaps/parcellate.py

Input data to be parcellated can be array-like but the neuromaps Parcellater will assume it's surface data.
I've modified the code such that an error is thrown when MNI152 data is provided as an `np.ndarray`. Volumetric data should instead be provided as a Nifti1Image. We don't convert the array to a Nifti1Image because the affine should be defined too. This PR was prompted by issue #122

[FIX] raise error when parcellating volumetric data defined as array

---

neuromaps/datasets/_osf.py
neuromaps/datasets/data/osf.json
neuromaps/stats.py

Added new PET receptor map for kappa-opioid. This map comes from Vijay et al 2018 Neuropsychopharmacology (thanks to Evan D Morris and Jocelyn Hoye for sharing it with us!).

[ENH] Add kappa-opioid receptor map

---

neuromaps/images.py

It seems error messages have changed, making the try-except catches invalid. 
Although not sure about if it would cause backward incompatibility, but for sufficiently new Python version it should be generally okay I guess?
We should probably refactor these in the future though.

[FIX] Fix doc load_data

---

neuromaps/datasets/_osf.py
neuromaps/datasets/annotations.py
neuromaps/datasets/atlases.py

In nilearn/nilearn/pull/4086 (first released with nilearn 0.10.3), 
- `nilearn.datasets.utils._fetch_files()` was refactored to `nilearn.datasets._utils.fetch_files()`
- `nilearn.datasets.utils._fetch_file()` was refactored to `nilearn.datasets._utils.fetch_single_file()`
- `nilearn.datasets.utils._md5_sum_file()` was refactored to `nilearn.datasets._utils._md5_sum_file()`

[FIX] Fix interface changes from nilearn

---

neuromaps/images.py

This PR refactors the `load_data` function to allow it's use for gifti images with more than one data array (e.g. for timeseries/functional data). There were a few issues with the function, which are related to how the `agg_data` method for GiftiImage objects (from nibabel) handles the intents of data arrays: when the intents of a data array is set to `NIFTI_INTENT_TIMESERIES`, the `agg_data` method returns a 2D ndarray, but when the intents are something else (e.g. `NIFTI_INTENT_SHAPE`), then the data arrays are returned as a tuple of multiple 1D array. The `load_data` was not working as expected in either of these cases (i.e. it couldn't load nor stack data images into numpy arrays).
This PR should fix Issue #139

[REF] Refactor load_data for gifti images with more than one data array

---

neuromaps/nulls/__init__.py
neuromaps/plotting.py

Fixing the error: `'Axes3D' object has no attribute '_generate_normals' in neuromaps.plotting.plot_surf_template` by bypassing the shading patch function. This may produce a slightly different figure than previous versions.
The functions have been moved out of the `Poly3DCollection` class to `mpl_toolkits.mplot3d.art3d`. One could try simply call the functions but it did not give nice results for me. Not planning to amend it unless there's a simple solution. 
Fixes #127

[FIX] Fix plotting issue

---

.github/workflows/tests.yml
neuromaps/images.py
neuromaps/stats.py
neuromaps/tests/conftest.py
neuromaps/tests/test_images.py

[MNT] Add Python 3.11 and 3.12 support

---

pyproject.toml

Updating `pyproject.toml` so that `docs` and `examples` folders will not appear in the top-level of `site-packages`.

[MNT] Update pyproject.toml

---

neuromaps/datasets/annotations.py
neuromaps/datasets/tests/test_annotations.py

Thanks to #185 for raising this issue.
The breaking change comes from nilearn/nilearn#4725, and first appears in [0.11.0](https://github.com/nilearn/nilearn/releases/tag/0.11.0).

[FIX] fix nilearn interface update for fetch_single_file
